export const IMAGES = {
    LOGO: require('../../assets/images/aspire_logo.png'),
    TOP_UP: require('../../assets/images/top_up.png'),
    WEEKLY_SPENDING: require('../../assets/images/weekly_spending.png'),
    FREEZE_CARD: require('../../assets/images/freeze_card.png'),
    GET_NEW_CARD: require('../../assets/images/get_new_card.png'),
    DEACTIVATED_CARDS: require('../../assets/images/deactivated_cards.png'),
    GET_NEW_CARD: require('../../assets/images/get_new_card.png'),
    ASPIRE: require('../../assets/images/aspire.png'),
    ASPIRE_ACTIVE: require('../../assets/images/aspire_active.png'),
    DEBIT_CARD: require('../../assets/images/debit_card.png'),
    DEBIT_CARD_ACTIVE: require('../../assets/images/debit_card_active.png'),
    PAYMENTS: require('../../assets/images/payments.png'),
    PAYMENTS_ACTIVE: require('../../assets/images/payments_active.png'),
    CREDIT: require('../../assets/images/credit.png'),
    CREDIT_ACTIVE: require('../../assets/images/credit_active.png'),
    PROFILE: require('../../assets/images/profile.png'),
    PROFILE_ACTIVE: require('../../assets/images/profile_active.png'),
    ASPIRE_WHITE: require('../../assets/images/aspire_white.png'),
    VISA: require('../../assets/images/visa.png'),
    METER: require('../../assets/images/meter.png'),
}