export const STRINGS = {
    DEBIT_CARD: 'Debit Card',
    AVAILABLE_BALANCE: 'Available balance',
    SD: 'S$',
    SHOW_CARD_NUMBER: 'Show card number',
    HIDE_CARD_NUMBER: 'Hide card number',
    TOP_UP_ACCOUNT_TITLE: 'Top-up account',
    TOP_UP_ACCOUNT_SUBTITLE: 'Deposit money to your account to use with card',
    WEEKLY_SPENDING_LIMIT_TITLE: 'Weekly spending limit',
    WEEKLY_SPENDING_LIMIT_SUBTITLE: 'You havn\'t set any spending limit on card',
    FREEZE_CARD_TITLE: 'Freeze card',
    FREEZE_CARD_SUBTITLE: 'Your debit card is currently active',
    GET_NEW_CARD_TITLE: 'Get a new card',
    GET_NEW_CARD_SUBTITLE: 'This deactivates your current debit card',
    DEACTIVATED_CARDS_TITLE: 'Deactivated cards',
    DEACTIVATED_CARDS_SUBTITLE: 'Your previously deactivated cards',
    ASPIRE: 'aspire',
    CVV: 'CVV: ',
    DATE: 'Thru: ',
    INTERNET_ERROR: 'Internet Not Connected',
    SPENDING_LIMIT: 'Spending limit',
    SET_WEEKLY_LIMIT: "Set a weekly debit card spending limit",
    WEEKLY_MEANS: 'Here weekly means the last 7 days - not the calendar week',
    SAVE: 'Save',
    SG_5: 'S$ 5,000',
    SG_10: 'S$ 10,000',
    SG_20: 'S$ 20,000',
    ENTER_AMOUNT: 'Enter amount',
    DEBIT_SPENDING_LIMIT: 'Debit card spending limit'
}
